/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Patungan;
import model.Member;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.EventListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Menu;
import model.Place;

/**
 *
 * @author dee
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        member = new javax.swing.JPanel();
        memberView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JList();
        btnAddMember = new javax.swing.JButton();
        btnEditMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        memberEdit = new javax.swing.JPanel();
        tfMemberEdit = new javax.swing.JTextField();
        labelMemberEdit = new javax.swing.JLabel();
        btnAddMemberEdit = new javax.swing.JButton();
        btnSaveMemberEdit = new javax.swing.JButton();
        btnCancelMemberEdit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        place = new javax.swing.JPanel();
        placeView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPlace = new javax.swing.JList();
        btnAddPlace = new javax.swing.JButton();
        btnEditPlace = new javax.swing.JButton();
        btnDeletePlace = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        placeEdit = new javax.swing.JPanel();
        labelPlaceEdit = new javax.swing.JLabel();
        tfPlaceEdit = new javax.swing.JTextField();
        btnAddPlaceEdit = new javax.swing.JButton();
        btnSavePlaceEdit = new javax.swing.JButton();
        btnCancelPlaceEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTaxPlaceEdit = new javax.swing.JFormattedTextField();
        menu = new javax.swing.JPanel();
        menuView = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddMenu = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnDeleteMenu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbPlaceMenu = new javax.swing.JComboBox();
        menuEdit = new javax.swing.JPanel();
        labelMenuEdit = new javax.swing.JLabel();
        tfMenuEdit = new javax.swing.JTextField();
        btnAddMenuEdit = new javax.swing.JButton();
        btnSaveMenuEdit = new javax.swing.JButton();
        btnCancelMenuEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spnQuantityMenuEdit = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        tfPriceMenuEdit = new javax.swing.JFormattedTextField();
        setMenu = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        menuSet = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMemberSet = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMenuSet = new javax.swing.JTable();
        btnSaveMenuSet = new javax.swing.JButton();
        btnBackMenuSet = new javax.swing.JButton();
        cbPlace = new javax.swing.JComboBox();
        summary = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMemberSummary = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMenuSummary = new javax.swing.JTable();
        payment = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblMemberPayment = new javax.swing.JTable();
        panelTotalMustPay = new javax.swing.JPanel();
        panelPaid = new javax.swing.JPanel();
        btnPayMember = new javax.swing.JButton();
        payMember = new javax.swing.JPanel();
        panelWhoPaid = new javax.swing.JPanel();
        panelTotal = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblMemberPaidBy = new javax.swing.JTable();
        btnDelMemberToPay = new javax.swing.JButton();
        btnAddMemberToPay = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        selectMemberToPay = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblMemberPayment2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnOkPayMember = new javax.swing.JButton();
        panelTotalMemberPaid = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        member.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Member List");

        listMember.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listMember.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(listMember);

        btnAddMember.setText("Add");

        btnEditMember.setText("Edit");

        btnDeleteMember.setText("Del");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout memberViewLayout = new javax.swing.GroupLayout(memberView);
        memberView.setLayout(memberViewLayout);
        memberViewLayout.setHorizontalGroup(
            memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(memberViewLayout.createSequentialGroup()
                        .addComponent(btnDeleteMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMember))
                    .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        memberViewLayout.setVerticalGroup(
            memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMember)
                    .addComponent(btnEditMember)
                    .addComponent(btnDeleteMember))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        member.add(memberView, "memberView");

        labelMemberEdit.setText("Add New Member");

        btnAddMemberEdit.setText("Add");

        btnSaveMemberEdit.setText("Save");

        btnCancelMemberEdit.setText("Cancel");

        jLabel14.setText("Member Name");

        javax.swing.GroupLayout memberEditLayout = new javax.swing.GroupLayout(memberEdit);
        memberEdit.setLayout(memberEditLayout);
        memberEditLayout.setHorizontalGroup(
            memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberEditLayout.createSequentialGroup()
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(tfMemberEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberEditLayout.createSequentialGroup()
                        .addContainerGap(151, Short.MAX_VALUE)
                        .addComponent(btnCancelMemberEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveMemberEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMemberEdit)
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addGroup(memberEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMemberEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        memberEditLayout.setVerticalGroup(
            memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMemberEdit)
                .addGap(8, 8, 8)
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMemberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMemberEdit)
                    .addComponent(btnSaveMemberEdit)
                    .addComponent(btnCancelMemberEdit))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        member.add(memberEdit, "memberEdit");

        jTabbedPane1.addTab("Member", member);

        place.setLayout(new java.awt.CardLayout());

        jLabel3.setText("Place List");

        listPlace.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listPlace.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(listPlace);

        btnAddPlace.setText("Add");

        btnEditPlace.setText("Edit");

        btnDeletePlace.setText("Del");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout placeViewLayout = new javax.swing.GroupLayout(placeView);
        placeView.setLayout(placeViewLayout);
        placeViewLayout.setHorizontalGroup(
            placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(placeViewLayout.createSequentialGroup()
                        .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(placeViewLayout.createSequentialGroup()
                                .addComponent(btnDeletePlace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditPlace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddPlace))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        placeViewLayout.setVerticalGroup(
            placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlace)
                    .addComponent(btnEditPlace)
                    .addComponent(btnDeletePlace))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        place.add(placeView, "placeView");

        labelPlaceEdit.setText("Add New Place");

        btnAddPlaceEdit.setText("Add");

        btnSavePlaceEdit.setText("Save");

        btnCancelPlaceEdit.setText("Cancel");

        jLabel5.setText("Tax");

        jLabel6.setText("Place Name");

        tfTaxPlaceEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tfTaxPlaceEdit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout placeEditLayout = new javax.swing.GroupLayout(placeEdit);
        placeEdit.setLayout(placeEditLayout);
        placeEditLayout.setHorizontalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPlaceEdit)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, placeEditLayout.createSequentialGroup()
                                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfTaxPlaceEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelPlaceEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSavePlaceEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addComponent(labelPlaceEdit)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        placeEditLayout.setVerticalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPlaceEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTaxPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelPlaceEdit)
                    .addComponent(btnSavePlaceEdit)
                    .addComponent(btnAddPlaceEdit))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        place.add(placeEdit, "placeEdit");

        jTabbedPane1.addTab("Place", place);

        menu.setLayout(new java.awt.CardLayout());

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblMenu);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        btnAddMenu.setText("Add");

        btnEditMenu.setText("Edit");

        btnDeleteMenu.setText("Del");

        jLabel15.setText("Place : ");

        cbPlaceMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout menuViewLayout = new javax.swing.GroupLayout(menuView);
        menuView.setLayout(menuViewLayout);
        menuViewLayout.setHorizontalGroup(
            menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuViewLayout.createSequentialGroup()
                        .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuViewLayout.createSequentialGroup()
                                .addComponent(btnDeleteMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddMenu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuViewLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPlaceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuViewLayout.setVerticalGroup(
            menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuViewLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbPlaceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMenu)
                    .addComponent(btnEditMenu)
                    .addComponent(btnDeleteMenu))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(menuView, "menuView");

        labelMenuEdit.setText("Add New Menu");

        btnAddMenuEdit.setText("Add");

        btnSaveMenuEdit.setText("Save");

        btnCancelMenuEdit.setText("Cancel");

        jLabel9.setText("Price");

        jLabel10.setText("Quantity");

        spnQuantityMenuEdit.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel16.setText("Nama Menu");

        tfPriceMenuEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tfPriceMenuEdit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPriceMenuEdit.setText("0");

        javax.swing.GroupLayout menuEditLayout = new javax.swing.GroupLayout(menuEdit);
        menuEdit.setLayout(menuEditLayout);
        menuEditLayout.setHorizontalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuEditLayout.createSequentialGroup()
                        .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addGap(30, 30, 30)
                        .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMenuEdit)
                            .addGroup(menuEditLayout.createSequentialGroup()
                                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnQuantityMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(menuEditLayout.createSequentialGroup()
                                        .addComponent(btnCancelMenuEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSaveMenuEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddMenuEdit)))
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addComponent(tfPriceMenuEdit)))
                    .addComponent(labelMenuEdit))
                .addContainerGap())
        );
        menuEditLayout.setVerticalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPriceMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnQuantityMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelMenuEdit)
                    .addComponent(btnSaveMenuEdit)
                    .addComponent(btnAddMenuEdit))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        menu.add(menuEdit, "menuEdit");

        jTabbedPane1.addTab("Menu", menu);

        setMenu.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("tab5", setMenu);

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.setLayout(new java.awt.CardLayout());

        tblMemberSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblMemberSet);

        tblMenuSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblMenuSet);

        btnSaveMenuSet.setText("Save");

        btnBackMenuSet.setText("Back");

        cbPlace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout menuSetLayout = new javax.swing.GroupLayout(menuSet);
        menuSet.setLayout(menuSetLayout);
        menuSetLayout.setHorizontalGroup(
            menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuSetLayout.createSequentialGroup()
                        .addComponent(btnBackMenuSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveMenuSet))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(cbPlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuSetLayout.setVerticalGroup(
            menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuSetLayout.createSequentialGroup()
                        .addComponent(cbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackMenuSet)
                    .addComponent(btnSaveMenuSet))
                .addContainerGap())
        );

        mainPanel.add(menuSet, "menuSet");

        tblMemberSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblMemberSummary);

        jLabel8.setText("Member List");

        jLabel12.setText("Menu List");

        tblMenuSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblMenuSummary);

        javax.swing.GroupLayout summaryLayout = new javax.swing.GroupLayout(summary);
        summary.setLayout(summaryLayout);
        summaryLayout.setHorizontalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        summaryLayout.setVerticalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(summary, "summary");

        jLabel13.setText("Member List");

        tblMemberPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblMemberPayment);

        panelTotalMustPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalMustPayLayout = new javax.swing.GroupLayout(panelTotalMustPay);
        panelTotalMustPay.setLayout(panelTotalMustPayLayout);
        panelTotalMustPayLayout.setHorizontalGroup(
            panelTotalMustPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTotalMustPayLayout.setVerticalGroup(
            panelTotalMustPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        panelPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelPaidLayout = new javax.swing.GroupLayout(panelPaid);
        panelPaid.setLayout(panelPaidLayout);
        panelPaidLayout.setHorizontalGroup(
            panelPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        panelPaidLayout.setVerticalGroup(
            panelPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        btnPayMember.setText("Pay Member");

        javax.swing.GroupLayout paymentLayout = new javax.swing.GroupLayout(payment);
        payment.setLayout(paymentLayout);
        paymentLayout.setHorizontalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTotalMustPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPayMember))))
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paymentLayout.setVerticalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(panelTotalMustPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayMember))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(payment, "payment");

        panelWhoPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelWhoPaidLayout = new javax.swing.GroupLayout(panelWhoPaid);
        panelWhoPaid.setLayout(panelWhoPaidLayout);
        panelWhoPaidLayout.setHorizontalGroup(
            panelWhoPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelWhoPaidLayout.setVerticalGroup(
            panelWhoPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        panelTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        tblMemberPaidBy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tblMemberPaidBy);

        btnDelMemberToPay.setText("Del");

        btnAddMemberToPay.setText("Add");

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Pay");

        btnPay.setText("Pay");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 107, Short.MAX_VALUE)
                        .addComponent(btnPay)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout payMemberLayout = new javax.swing.GroupLayout(payMember);
        payMember.setLayout(payMemberLayout);
        payMemberLayout.setHorizontalGroup(
            payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWhoPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(payMemberLayout.createSequentialGroup()
                        .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(payMemberLayout.createSequentialGroup()
                                .addComponent(btnDelMemberToPay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddMemberToPay))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        payMemberLayout.setVerticalGroup(
            payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWhoPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(payMemberLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelMemberToPay)
                    .addComponent(btnAddMemberToPay))
                .addGap(9, 9, 9))
        );

        mainPanel.add(payMember, "card11");

        tblMemberPayment2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(tblMemberPayment2);

        jLabel4.setText("List Member");

        btnOkPayMember.setText("OK");

        panelTotalMemberPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalMemberPaidLayout = new javax.swing.GroupLayout(panelTotalMemberPaid);
        panelTotalMemberPaid.setLayout(panelTotalMemberPaidLayout);
        panelTotalMemberPaidLayout.setHorizontalGroup(
            panelTotalMemberPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        panelTotalMemberPaidLayout.setVerticalGroup(
            panelTotalMemberPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selectMemberToPayLayout = new javax.swing.GroupLayout(selectMemberToPay);
        selectMemberToPay.setLayout(selectMemberToPayLayout);
        selectMemberToPayLayout.setHorizontalGroup(
            selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectMemberToPayLayout.createSequentialGroup()
                        .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                                .addGap(0, 69, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66))
                            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(panelTotalMemberPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectMemberToPayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkPayMember)))
                .addContainerGap())
        );
        selectMemberToPayLayout.setVerticalGroup(
            selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(selectMemberToPayLayout.createSequentialGroup()
                        .addComponent(panelTotalMemberPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkPayMember)
                .addContainerGap())
        );

        mainPanel.add(selectMemberToPay, "selectMemberToPay");

        jTabbedPane1.addTab("tab3", mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnAddMemberEdit;
    private javax.swing.JButton btnAddMemberToPay;
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnAddMenuEdit;
    private javax.swing.JButton btnAddPlace;
    private javax.swing.JButton btnAddPlaceEdit;
    private javax.swing.JButton btnBackMenuSet;
    private javax.swing.JButton btnCancelMemberEdit;
    private javax.swing.JButton btnCancelMenuEdit;
    private javax.swing.JButton btnCancelPlaceEdit;
    private javax.swing.JButton btnDelMemberToPay;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JButton btnDeletePlace;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnEditPlace;
    private javax.swing.JButton btnOkPayMember;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPayMember;
    private javax.swing.JButton btnSaveMemberEdit;
    private javax.swing.JButton btnSaveMenuEdit;
    private javax.swing.JButton btnSaveMenuSet;
    private javax.swing.JButton btnSavePlaceEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbPlace;
    private javax.swing.JComboBox cbPlaceMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelMemberEdit;
    private javax.swing.JLabel labelMenuEdit;
    private javax.swing.JLabel labelPlaceEdit;
    private javax.swing.JList listMember;
    private javax.swing.JList listPlace;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel member;
    private javax.swing.JPanel memberEdit;
    private javax.swing.JPanel memberView;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuEdit;
    private javax.swing.JPanel menuSet;
    private javax.swing.JPanel menuView;
    private javax.swing.JPanel panelPaid;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JPanel panelTotalMemberPaid;
    private javax.swing.JPanel panelTotalMustPay;
    private javax.swing.JPanel panelWhoPaid;
    private javax.swing.JPanel payMember;
    private javax.swing.JPanel payment;
    private javax.swing.JPanel place;
    private javax.swing.JPanel placeEdit;
    private javax.swing.JPanel placeView;
    private javax.swing.JPanel selectMemberToPay;
    private javax.swing.JPanel setMenu;
    private javax.swing.JSpinner spnQuantityMenuEdit;
    private javax.swing.JPanel summary;
    private javax.swing.JTable tblMemberPaidBy;
    private javax.swing.JTable tblMemberPayment;
    private javax.swing.JTable tblMemberPayment2;
    private javax.swing.JTable tblMemberSet;
    private javax.swing.JTable tblMemberSummary;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblMenuSet;
    private javax.swing.JTable tblMenuSummary;
    private javax.swing.JTextField tfMemberEdit;
    private javax.swing.JTextField tfMenuEdit;
    private javax.swing.JTextField tfPlaceEdit;
    private javax.swing.JFormattedTextField tfPriceMenuEdit;
    private javax.swing.JFormattedTextField tfTaxPlaceEdit;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        Home h = new Home();
        h.setVisible(true);
    }

    private Controller c;

    public Home() {
        initComponents();
        c = new Controller();
    }

    public void setListener(EventListener event) {
        btnAddMember.addActionListener((ActionListener) event);
        btnAddMemberEdit.addActionListener((ActionListener) event);
        btnAddMemberToPay.addActionListener((ActionListener) event);
        btnAddMenu.addActionListener((ActionListener) event);
        btnAddMenuEdit.addActionListener((ActionListener) event);
        btnAddPlace.addActionListener((ActionListener) event);
        btnAddPlaceEdit.addActionListener((ActionListener) event);
        btnBackMenuSet.addActionListener((ActionListener) event);
        btnCancelMemberEdit.addActionListener((ActionListener) event);
        btnCancelMenuEdit.addActionListener((ActionListener) event);
        btnCancelPlaceEdit.addActionListener((ActionListener) event);
        btnDelMemberToPay.addActionListener((ActionListener) event);
        btnDeleteMember.addActionListener((ActionListener) event);
        btnDeleteMenu.addActionListener((ActionListener) event);
        btnDeletePlace.addActionListener((ActionListener) event);
        btnEditMember.addActionListener((ActionListener) event);
        btnEditMenu.addActionListener((ActionListener) event);
        btnEditPlace.addActionListener((ActionListener) event);
        btnOkPayMember.addActionListener((ActionListener) event);
        btnPay.addActionListener((ActionListener) event);
        btnPayMember.addActionListener((ActionListener) event);
        btnSaveMemberEdit.addActionListener((ActionListener) event);
        btnSaveMenuEdit.addActionListener((ActionListener) event);
        btnSaveMenuSet.addActionListener((ActionListener) event);
        btnSavePlaceEdit.addActionListener((ActionListener) event);
        btnSetBuyer.addActionListener((ActionListener) event);
        btnSetMenu.addActionListener((ActionListener) event);

        listMember.addMouseListener((MouseAdapter) event);
        listPlace.addMouseListener((MouseAdapter) event);
        tblMenu.addMouseListener((MouseAdapter) event);

        tfMemberEdit.addActionListener((ActionListener) event);

        tfPlaceEdit.addActionListener((ActionListener) event);
        tfTaxPlaceEdit.addActionListener((ActionListener) event);

        cbPlace.addActionListener((ActionListener) event);
    }

    private class Controller extends MouseAdapter implements ActionListener {

        private CardLayout c = (CardLayout) mainPanel.getLayout();
        private Patungan p = new Patungan();
        private int lastSelectedListMember = -1;
        private int lastSelectedListPlace = -1;
        private int lastSelectedTableMenu = -1;
        private Place tempPlace;

        public Controller() {
            setListener(this);
            gotoMemberView();
        }

        public void gotoMemberView() {
            c.show(mainPanel, "memberView");
            listMember.setListData(p.getListMemberName());
            btnAddMember.requestFocus();
            lastSelectedListMember = -1;
            listMember.clearSelection();
            btnAddMember.setVisible(true);
            btnEditMember.setVisible(false);
            btnDeleteMember.setVisible(false);
        }

        public void gotoMemberEdit(int id) {
            c.show(mainPanel, "memberEdit");
            tfMemberEdit.requestFocus();
            if (id == -1) {
                lastSelectedListMember = -1;
                tfMemberEdit.setText("");
                labelMemberEdit.setText("Add New Member");
                btnAddMemberEdit.setVisible(true);
                btnSaveMemberEdit.setVisible(false);
            } else {
                tfMemberEdit.setText(p.getMember(id).getName());
                labelMemberEdit.setText("Edit Member");
                btnAddMemberEdit.setVisible(false);
                btnSaveMemberEdit.setVisible(true);
            }
        }

        public void gotoPlaceView() {
            c.show(mainPanel, "placeView");
            lastSelectedListPlace = -1;
            listPlace.setListData(p.getListPlaceName());
            btnAddPlace.requestFocus();
            listPlace.clearSelection();
            btnAddPlace.setVisible(true);
            btnDeletePlace.setVisible(false);
            btnEditPlace.setVisible(false);
            btnSetMenu.setVisible(false);
        }

        public void gotoPlaceEdit(int id) {
            c.show(mainPanel, "placeEdit");
            tfPlaceEdit.requestFocus();
            if (id == -1) {
                lastSelectedListPlace = -1;
                tfPlaceEdit.setText("");
                tfTaxPlaceEdit.setText("0");
                labelPlaceEdit.setText("Add New Place");
                btnAddPlaceEdit.setVisible(true);
                btnSavePlaceEdit.setVisible(false);
            } else {
                Place pl = p.getPlace(id);
                tfPlaceEdit.setText(pl.getName());
                tfTaxPlaceEdit.setText(String.valueOf(pl.getTax()));
                labelPlaceEdit.setText("Edit Place");
                btnAddPlaceEdit.setVisible(false);
                btnSavePlaceEdit.setVisible(true);
            }
        }

        public void gotoMenuView() {
            c.show(mainPanel, "menuView");
            setTable("Menu List", tempPlace.getListMenuName(), tblMenu);
            lastSelectedTableMenu = -1;
            lblPlaceName.setText(tempPlace.getName());
            tblMenu.clearSelection();
            btnAddMenu.setVisible(true);
            btnDeleteMenu.setVisible(false);
            btnEditMenu.setVisible(false);
            btnSetBuyer.setVisible(false);
        }

        public void gotoMenuEdit(int id) {
            c.show(mainPanel, "menuEdit");
            tfMenuEdit.requestFocus();
            if (id == -1) {
                lastSelectedTableMenu = -1;
                tfMenuEdit.setText("");
                tfPriceMenuEdit.setText("0");
                labelMenuEdit.setText("Add New Menu");
                btnAddMenuEdit.setVisible(true);
                btnSaveMenuEdit.setVisible(false);
            } else {
                tfMenuEdit.setText(tempPlace.getMenu(id).getName());
                tfPriceMenuEdit.setText(String.valueOf(tempPlace.getMenu(id).getPrice()));
                labelMenuEdit.setText("Edit Menu");
                btnAddMenuEdit.setVisible(false);
                btnSaveMenuEdit.setVisible(true);
            }
            spnQuantityMenuEdit.setValue(1);
        }

        public void gotoMenuSet() {
            c.show(mainPanel, "menuSet");
            cbPlace.removeAllItems();
            String[] data = p.getListPlaceName();
            for (String d : data) {
                cbPlace.addItem(d);
            }
            setTable("Member List", p.getListMemberName(), tblMemberSet);
            setTable("Menu List", p.getPlace(0).getListMenuName(), tblMenuSet);
        }

        public void setTable(String title, String[] data, JTable table) {
            String[][] content = new String[data.length][1];
            for (int i = 0; i < data.length; i++) {
                content[i][0] = data[i];
            }
            DefaultTableModel tableModel = new DefaultTableModel(content, new String[]{title});
            table.setModel(tableModel);
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            Object e = ae.getSource();

            //Action Handler for Panel Member View
            if (e.equals(btnAddMember)) {
                gotoMemberEdit(-1);
            } else if (e.equals(btnEditMember)) {
                gotoMemberEdit(lastSelectedListMember); //
            } else if (e.equals(btnDeleteMember)) {
                String message = "Delete member " + p.getMember(lastSelectedListMember).getName() + "?";
                String title = "Confirm Delete Member";
                int reply = JOptionPane.showConfirmDialog(Home.this, message, title, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    p.delMember(lastSelectedListMember);
                }
                listMember.setListData(p.getListMemberName());
            } //
            //Action Handler for Panel Member Edit =====================================================================
            //
            else if (e.equals(btnCancelMemberEdit)) {
                gotoMemberView();
            } else if ((e.equals(btnAddMemberEdit)) || ((e.equals(tfMemberEdit)) && (lastSelectedListMember < 0))) {
                if ((tfMemberEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Member name must not be empty");
                } else {
                    p.addMember(new Member(tfMemberEdit.getText()));
                    gotoMemberView();
                }
            } else if ((e.equals(btnSaveMemberEdit)) || ((e.equals(tfMemberEdit)) && (lastSelectedListMember >= 0))) {
                if ((tfMemberEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Member name must not be empty");
                } else {
                    p.getMember(lastSelectedListMember).setName(tfMemberEdit.getText());
                    gotoMemberView();
                }
            }//
            //Action Handler for Panel Place View =====================================================================
            //
            else if (e.equals(btnAddPlace)) {
                gotoPlaceEdit(-1);
            } else if (e.equals(btnEditPlace)) {
                gotoPlaceEdit(lastSelectedListPlace);
            } else if (e.equals(btnDeletePlace)) {
                String message = "Delete place " + p.getPlace(lastSelectedListPlace).getName() + "?";
                String title = "Confirm Delete Place";
                int reply = JOptionPane.showConfirmDialog(Home.this, message, title, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    p.delPlace(lastSelectedListPlace);
                }
                listPlace.setListData(p.getListPlaceName());
            } else if (e.equals(btnSetMenu)) {
                tempPlace = p.getPlace(lastSelectedListPlace);
                gotoMenuView();
            }//
            //Action Handler for Panel Place Edit =====================================================================
            //
            else if (e.equals(btnCancelPlaceEdit)) {
                gotoPlaceView();
            } else if (e.equals((btnAddPlaceEdit)) || ((e.equals(tfPlaceEdit) || e.equals(tfTaxPlaceEdit)) && (lastSelectedListPlace < 0))) {
                if ((tfPlaceEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Place name must not be empty");
                } else if (tfTaxPlaceEdit.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Tax must a number");
                } else {
                    p.addPlace(new Place(tfPlaceEdit.getText(), Double.parseDouble(tfTaxPlaceEdit.getText())));
                    gotoPlaceView();
                }
            } else if ((e.equals(btnSavePlaceEdit)) || ((e.equals(tfPlaceEdit) || e.equals(tfTaxPlaceEdit)) && (lastSelectedListPlace >= 0))) {
                if ((tfPlaceEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Place name must not be empty");
                } else if ((tfTaxPlaceEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Tax must be a number");
                } else {
                    Place pl = p.getPlace(lastSelectedListPlace);
                    pl.setName(tfPlaceEdit.getText());
                    pl.setTax(Double.parseDouble(tfTaxPlaceEdit.getText()));
                    gotoPlaceView();
                }
            } //
            //Action Handler for Panel Menu View =====================================================================
            //
            else if (e.equals(btnAddMenu)) {
                gotoMenuEdit(-1);
            } else if (e.equals(btnEditMenu)) {
                gotoMenuEdit(lastSelectedTableMenu);
            } else if (e.equals(btnDeleteMenu)) {
                String message = "Delete Menu " + tempPlace.getMenu(lastSelectedTableMenu).getName() + "?";
                String title = "Confirm Delete Menu";
                int reply = JOptionPane.showConfirmDialog(Home.this, message, title, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    tempPlace.delMenu(lastSelectedTableMenu);
                }
//                viewTableMenu();
                setTable("Menu List", tempPlace.getListMenuName(), tblMenu);
            } else if (e.equals(btnSetBuyer)) {
                tempPlace = p.getPlace(lastSelectedListPlace);
                System.out.println("ok");
                gotoMenuSet();
            }//
            //Action Handler for Panel Menu Edit =====================================================================
            //
            else if (e.equals(btnCancelMenuEdit)) {
                gotoMenuView();
            } else if (e.equals(btnAddMenuEdit)) {
                if ((tfMenuEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Menu name must not be empty");
                } else if ((tfPriceMenuEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Menu price must be a number");
                } else {
                    int qty = (int) spnQuantityMenuEdit.getValue();
                    for (int i = 0; i < qty; i++) {
                        tempPlace.addMenu(new Menu(tfMenuEdit.getText(), Double.parseDouble(tfPriceMenuEdit.getText()),
                                tempPlace.getTax()));
                    }
                    gotoMenuView();
                }
            } else if (e.equals(btnSaveMenuEdit)) {
                if ((tfMenuEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Menu name must not be empty");
                } else if ((tfPriceMenuEdit.getText().replaceAll(" ", "")).isEmpty()) {
                    JOptionPane.showMessageDialog(Home.this, "Menu price must be a number");
                } else {
                    Menu m = tempPlace.getMenu(lastSelectedTableMenu);
                    m.setName(tfMenuEdit.getText());
                    m.setPrice(Double.parseDouble(tfPriceMenuEdit.getText()));
                    int qty = (int) spnQuantityMenuEdit.getValue();
                    if (qty > 1) {
                        for (int i = 0; i < qty - 1; i++) {
                            tempPlace.addMenu(new Menu(tfMenuEdit.getText(), Double.parseDouble(tfPriceMenuEdit.getText()),
                                    tempPlace.getTax()));
                        }
                    }
                    gotoMenuView();
                }
            }//
            //Action Handler for Panel Menu Set =====================================================================
            //
            else if (e.equals(cbPlace)) {
                if (cbPlace.getSelectedIndex() > -1) {
                    setTable("Menu List", p.getPlace(cbPlace.getSelectedIndex()).getListMenuName(), tblMenuSet);
                }
            }
        }

        @Override
        public void mousePressed(MouseEvent me) {
            Object e = me.getSource();
            //Action Handler for Panel Member View =====================================================================
            if (e.equals(listMember)) {
                int index = listMember.locationToIndex(me.getPoint());
                if ((index != -1 && index == lastSelectedListMember) || (listMember.getModel().getSize() == 0)) {
                    listMember.clearSelection();
                    btnEditMember.setVisible(false);
                    btnDeleteMember.setVisible(false);
                } else {
                    btnEditMember.setVisible(true);
                    btnDeleteMember.setVisible(true);
                }
                lastSelectedListMember = listMember.getSelectedIndex();
            }//
            //Action Handler for Panel Member View =====================================================================
            //
            else if (e.equals(listPlace)) {
                int index = listPlace.locationToIndex(me.getPoint());
                if ((index != -1 && index == lastSelectedListPlace) || (listPlace.getModel().getSize() == 0)) {
                    listPlace.clearSelection();
                    btnEditPlace.setVisible(false);
                    btnDeletePlace.setVisible(false);
                    btnSetMenu.setVisible(false);
                } else {
                    btnEditPlace.setVisible(true);
                    btnDeletePlace.setVisible(true);
                    btnSetMenu.setVisible(true);
                }
                lastSelectedListPlace = listPlace.getSelectedIndex();
            }//
            //Action Handler for Panel Menu View =====================================================================
            //
            else if (e.equals(tblMenu)) {
                int index = tblMenu.getSelectedRow();
                if ((index != -1 && index == lastSelectedTableMenu) || (tblMenu.getRowCount() == 0)) {
                    tblMenu.clearSelection();
                    btnEditMenu.setVisible(false);
                    btnDeleteMenu.setVisible(false);
                    btnSetBuyer.setVisible(false);
                } else {
                    btnEditMenu.setVisible(true);
                    btnDeleteMenu.setVisible(true);
                    btnSetBuyer.setVisible(true);
                }
                lastSelectedTableMenu = tblMenu.getSelectedRow();
            }
        }
    }
}
