/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewNew;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.EventListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import patungan.Patungan;

/**
 *
 * @author dee
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        memberView = new javax.swing.JPanel();
        btnEditMember = new javax.swing.JButton();
        btnAddMember = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JList();
        btnDeleteMember = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        placeView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPlace = new javax.swing.JList();
        btnAddPlace = new javax.swing.JButton();
        btnEditPlace = new javax.swing.JButton();
        btnDeletePlace = new javax.swing.JButton();
        btnSetMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuView = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnDeleteMenu = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnAddMenu = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnSetBuyer = new javax.swing.JButton();
        placeEdit = new javax.swing.JPanel();
        labelPlaceEdit = new javax.swing.JLabel();
        tfPlaceEdit = new javax.swing.JTextField();
        btnAddPlaceEdit = new javax.swing.JButton();
        btnSavePlaceEdit = new javax.swing.JButton();
        btnCancelPlaceEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfTaxPlaceEdit = new javax.swing.JTextField();
        memberEdit = new javax.swing.JPanel();
        labelMemberEdit = new javax.swing.JLabel();
        tfMemberEdit = new javax.swing.JTextField();
        btnAddMemberEdit = new javax.swing.JButton();
        btnSaveMemberEdit = new javax.swing.JButton();
        btnCancelMemberEdit = new javax.swing.JButton();
        menuEdit = new javax.swing.JPanel();
        labelMenuEdit = new javax.swing.JLabel();
        tfMenuEdit = new javax.swing.JTextField();
        btnAddMenuEdit = new javax.swing.JButton();
        btnSaveMenuEdit = new javax.swing.JButton();
        btnCancelMenuEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfPriceMenuEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spnQuantityMenuEdit = new javax.swing.JSpinner();
        menuSet = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMemberSet = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMenuSet = new javax.swing.JTable();
        btnSaveMenuSet = new javax.swing.JButton();
        btnBackMenuSet = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        summary = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMemberSummary = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMenuSummary = new javax.swing.JTable();
        payment = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblMemberPayment = new javax.swing.JTable();
        panelTotalMustPay = new javax.swing.JPanel();
        panelPaid = new javax.swing.JPanel();
        btnPayMember = new javax.swing.JButton();
        payMember = new javax.swing.JPanel();
        panelWhoPaid = new javax.swing.JPanel();
        panelTotal = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblMemberPaidBy = new javax.swing.JTable();
        btnDelMemberToPay = new javax.swing.JButton();
        btnAddMemberToPay = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        selectMemberToPay = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblMemberPayment2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnOkPayMember = new javax.swing.JButton();
        panelTotalMemberPaid = new javax.swing.JPanel();
        menuMember = new javax.swing.JToggleButton();
        menuPlace = new javax.swing.JToggleButton();
        menuPayment = new javax.swing.JToggleButton();
        menuSummary = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.setLayout(new java.awt.CardLayout());

        btnEditMember.setText("Edit");

        btnAddMember.setText("Add");

        jLabel1.setText("Member List");

        listMember.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMember);

        btnDeleteMember.setText("Del");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout memberViewLayout = new javax.swing.GroupLayout(memberView);
        memberView.setLayout(memberViewLayout);
        memberViewLayout.setHorizontalGroup(
            memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(memberViewLayout.createSequentialGroup()
                        .addComponent(btnDeleteMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMember))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        memberViewLayout.setVerticalGroup(
            memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMember)
                    .addComponent(btnEditMember)
                    .addComponent(btnAddMember))
                .addContainerGap())
        );

        mainPanel.add(memberView, "memberView");

        jLabel3.setText("Place List");

        listPlace.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listPlace);

        btnAddPlace.setText("Add");

        btnEditPlace.setText("Edit");

        btnDeletePlace.setText("Del");

        btnSetMenu.setText("Set Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout placeViewLayout = new javax.swing.GroupLayout(placeView);
        placeView.setLayout(placeViewLayout);
        placeViewLayout.setHorizontalGroup(
            placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placeViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(287, 287, 287))
            .addGroup(placeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(placeViewLayout.createSequentialGroup()
                        .addComponent(btnDeletePlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPlace)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeViewLayout.createSequentialGroup()
                        .addComponent(btnSetMenu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        placeViewLayout.setVerticalGroup(
            placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletePlace)
                    .addComponent(btnEditPlace)
                    .addComponent(btnAddPlace)
                    .addComponent(btnSetMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(placeView, "placeView");

        jLabel6.setText("List Menu");

        btnDeleteMenu.setText("Del");

        btnEditMenu.setText("Edit");

        btnAddMenu.setText("Add");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblMenu);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnSetBuyer.setText("Set Buyer");

        javax.swing.GroupLayout menuViewLayout = new javax.swing.GroupLayout(menuView);
        menuView.setLayout(menuViewLayout);
        menuViewLayout.setHorizontalGroup(
            menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(menuViewLayout.createSequentialGroup()
                            .addComponent(btnDeleteMenu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditMenu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddMenu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuViewLayout.createSequentialGroup()
                        .addComponent(btnSetBuyer)
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuViewLayout.setVerticalGroup(
            menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMenu)
                    .addComponent(btnEditMenu)
                    .addComponent(btnDeleteMenu)
                    .addComponent(btnSetBuyer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(menuView, "menuView");

        labelPlaceEdit.setText("Add New Place");

        btnAddPlaceEdit.setText("Add");

        btnSavePlaceEdit.setText("Save");

        btnCancelPlaceEdit.setText("Cancel");

        jLabel5.setText("Tax");

        javax.swing.GroupLayout placeEditLayout = new javax.swing.GroupLayout(placeEdit);
        placeEdit.setLayout(placeEditLayout);
        placeEditLayout.setHorizontalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(placeEditLayout.createSequentialGroup()
                        .addComponent(labelPlaceEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfTaxPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, placeEditLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(btnCancelPlaceEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSavePlaceEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddPlaceEdit))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        placeEditLayout.setVerticalGroup(
            placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeEditLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlaceEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTaxPlaceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlaceEdit)
                    .addComponent(btnSavePlaceEdit)
                    .addComponent(btnCancelPlaceEdit))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        mainPanel.add(placeEdit, "placeEdit");

        labelMemberEdit.setText("Add New Member");

        btnAddMemberEdit.setText("Add");

        btnSaveMemberEdit.setText("Save");

        btnCancelMemberEdit.setText("Cancel");

        javax.swing.GroupLayout memberEditLayout = new javax.swing.GroupLayout(memberEdit);
        memberEdit.setLayout(memberEditLayout);
        memberEditLayout.setHorizontalGroup(
            memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberEditLayout.createSequentialGroup()
                        .addComponent(labelMemberEdit)
                        .addGap(18, 18, 18)
                        .addComponent(tfMemberEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberEditLayout.createSequentialGroup()
                        .addGap(0, 118, Short.MAX_VALUE)
                        .addComponent(btnCancelMemberEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveMemberEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMemberEdit)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        memberEditLayout.setVerticalGroup(
            memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberEditLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMemberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMemberEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMemberEdit)
                    .addComponent(btnSaveMemberEdit)
                    .addComponent(btnCancelMemberEdit))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        mainPanel.add(memberEdit, "memberEdit");

        labelMenuEdit.setText("Add New Menu");

        btnAddMenuEdit.setText("Add");

        btnSaveMenuEdit.setText("Save");

        btnCancelMenuEdit.setText("Cancel");

        jLabel9.setText("Price");

        jLabel10.setText("Quantity");

        javax.swing.GroupLayout menuEditLayout = new javax.swing.GroupLayout(menuEdit);
        menuEdit.setLayout(menuEditLayout);
        menuEditLayout.setHorizontalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuEditLayout.createSequentialGroup()
                        .addComponent(labelMenuEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuEditLayout.createSequentialGroup()
                        .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(82, 82, 82)
                        .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPriceMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnQuantityMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEditLayout.createSequentialGroup()
                        .addComponent(btnCancelMenuEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveMenuEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMenuEdit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuEditLayout.setVerticalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEditLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMenuEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPriceMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnQuantityMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMenuEdit)
                    .addComponent(btnSaveMenuEdit)
                    .addComponent(btnCancelMenuEdit))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        mainPanel.add(menuEdit, "menuEdit");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jLabel7.setText("Member List");

        tblMemberSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblMemberSet);

        tblMenuSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblMenuSet);

        btnSaveMenuSet.setText("Save");

        btnBackMenuSet.setText("Back");
        btnBackMenuSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuSetActionPerformed(evt);
            }
        });

        jLabel11.setText("Menu List");

        javax.swing.GroupLayout menuSetLayout = new javax.swing.GroupLayout(menuSet);
        menuSet.setLayout(menuSetLayout);
        menuSetLayout.setHorizontalGroup(
            menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuSetLayout.createSequentialGroup()
                        .addComponent(btnBackMenuSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveMenuSet))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menuSetLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuSetLayout.setVerticalGroup(
            menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSetLayout.createSequentialGroup()
                .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuSetLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(1, 1, 1)
                        .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuSetLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBackMenuSet)
                            .addComponent(btnSaveMenuSet)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuSetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        mainPanel.add(menuSet, "menuSet");

        tblMemberSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblMemberSummary);

        jLabel8.setText("Member List");

        jLabel12.setText("Menu List");

        tblMenuSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblMenuSummary);

        javax.swing.GroupLayout summaryLayout = new javax.swing.GroupLayout(summary);
        summary.setLayout(summaryLayout);
        summaryLayout.setHorizontalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        summaryLayout.setVerticalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(summary, "summary");

        jLabel13.setText("Member List");

        tblMemberPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblMemberPayment);

        panelTotalMustPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalMustPayLayout = new javax.swing.GroupLayout(panelTotalMustPay);
        panelTotalMustPay.setLayout(panelTotalMustPayLayout);
        panelTotalMustPayLayout.setHorizontalGroup(
            panelTotalMustPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTotalMustPayLayout.setVerticalGroup(
            panelTotalMustPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        panelPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelPaidLayout = new javax.swing.GroupLayout(panelPaid);
        panelPaid.setLayout(panelPaidLayout);
        panelPaidLayout.setHorizontalGroup(
            panelPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        panelPaidLayout.setVerticalGroup(
            panelPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        btnPayMember.setText("Pay Member");

        javax.swing.GroupLayout paymentLayout = new javax.swing.GroupLayout(payment);
        payment.setLayout(paymentLayout);
        paymentLayout.setHorizontalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTotalMustPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPayMember))))
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paymentLayout.setVerticalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addComponent(panelTotalMustPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayMember))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(payment, "payment");

        panelWhoPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelWhoPaidLayout = new javax.swing.GroupLayout(panelWhoPaid);
        panelWhoPaid.setLayout(panelWhoPaidLayout);
        panelWhoPaidLayout.setHorizontalGroup(
            panelWhoPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelWhoPaidLayout.setVerticalGroup(
            panelWhoPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        panelTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        tblMemberPaidBy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tblMemberPaidBy);

        btnDelMemberToPay.setText("Del");

        btnAddMemberToPay.setText("Add");

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Pay");

        btnPay.setText("Pay");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addComponent(btnPay)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout payMemberLayout = new javax.swing.GroupLayout(payMember);
        payMember.setLayout(payMemberLayout);
        payMemberLayout.setHorizontalGroup(
            payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWhoPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(payMemberLayout.createSequentialGroup()
                        .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(payMemberLayout.createSequentialGroup()
                                .addComponent(btnDelMemberToPay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddMemberToPay))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        payMemberLayout.setVerticalGroup(
            payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWhoPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(payMemberLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelMemberToPay)
                    .addComponent(btnAddMemberToPay))
                .addGap(9, 9, 9))
        );

        mainPanel.add(payMember, "card11");

        tblMemberPayment2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(tblMemberPayment2);

        jLabel4.setText("List Member");

        btnOkPayMember.setText("OK");

        panelTotalMemberPaid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTotalMemberPaidLayout = new javax.swing.GroupLayout(panelTotalMemberPaid);
        panelTotalMemberPaid.setLayout(panelTotalMemberPaidLayout);
        panelTotalMemberPaidLayout.setHorizontalGroup(
            panelTotalMemberPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        panelTotalMemberPaidLayout.setVerticalGroup(
            panelTotalMemberPaidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selectMemberToPayLayout = new javax.swing.GroupLayout(selectMemberToPay);
        selectMemberToPay.setLayout(selectMemberToPayLayout);
        selectMemberToPayLayout.setHorizontalGroup(
            selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectMemberToPayLayout.createSequentialGroup()
                        .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                                .addGap(0, 55, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66))
                            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(panelTotalMemberPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectMemberToPayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkPayMember)))
                .addContainerGap())
        );
        selectMemberToPayLayout.setVerticalGroup(
            selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMemberToPayLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(selectMemberToPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addGroup(selectMemberToPayLayout.createSequentialGroup()
                        .addComponent(panelTotalMemberPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkPayMember)
                .addContainerGap())
        );

        mainPanel.add(selectMemberToPay, "selectMemberToPay");

        buttonGroup1.add(menuMember);
        menuMember.setSelected(true);
        menuMember.setText("Member");
        menuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMemberActionPerformed(evt);
            }
        });

        buttonGroup1.add(menuPlace);
        menuPlace.setText("Place");
        menuPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlaceActionPerformed(evt);
            }
        });

        buttonGroup1.add(menuPayment);
        menuPayment.setText("Payment");
        menuPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaymentActionPerformed(evt);
            }
        });

        buttonGroup1.add(menuSummary);
        menuSummary.setText("Summary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuSummary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuPayment)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuMember)
                    .addComponent(menuPlace)
                    .addComponent(menuPayment)
                    .addComponent(menuSummary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPlaceActionPerformed

    private void menuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMemberActionPerformed

    private void menuPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPaymentActionPerformed

    private void btnBackMenuSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMenuSetActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnAddMemberEdit;
    private javax.swing.JButton btnAddMemberToPay;
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnAddMenuEdit;
    private javax.swing.JButton btnAddPlace;
    private javax.swing.JButton btnAddPlaceEdit;
    private javax.swing.JButton btnBackMenuSet;
    private javax.swing.JButton btnCancelMemberEdit;
    private javax.swing.JButton btnCancelMenuEdit;
    private javax.swing.JButton btnCancelPlaceEdit;
    private javax.swing.JButton btnDelMemberToPay;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JButton btnDeletePlace;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnEditPlace;
    private javax.swing.JButton btnOkPayMember;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPayMember;
    private javax.swing.JButton btnSaveMemberEdit;
    private javax.swing.JButton btnSaveMenuEdit;
    private javax.swing.JButton btnSaveMenuSet;
    private javax.swing.JButton btnSavePlaceEdit;
    private javax.swing.JButton btnSetBuyer;
    private javax.swing.JButton btnSetMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelMemberEdit;
    private javax.swing.JLabel labelMenuEdit;
    private javax.swing.JLabel labelPlaceEdit;
    private javax.swing.JList listMember;
    private javax.swing.JList listPlace;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberEdit;
    private javax.swing.JPanel memberView;
    private javax.swing.JPanel menuEdit;
    private javax.swing.JToggleButton menuMember;
    private javax.swing.JToggleButton menuPayment;
    private javax.swing.JToggleButton menuPlace;
    private javax.swing.JPanel menuSet;
    private javax.swing.JToggleButton menuSummary;
    private javax.swing.JPanel menuView;
    private javax.swing.JPanel panelPaid;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JPanel panelTotalMemberPaid;
    private javax.swing.JPanel panelTotalMustPay;
    private javax.swing.JPanel panelWhoPaid;
    private javax.swing.JPanel payMember;
    private javax.swing.JPanel payment;
    private javax.swing.JPanel placeEdit;
    private javax.swing.JPanel placeView;
    private javax.swing.JPanel selectMemberToPay;
    private javax.swing.JSpinner spnQuantityMenuEdit;
    private javax.swing.JPanel summary;
    private javax.swing.JTable tblMemberPaidBy;
    private javax.swing.JTable tblMemberPayment;
    private javax.swing.JTable tblMemberPayment2;
    private javax.swing.JTable tblMemberSet;
    private javax.swing.JTable tblMemberSummary;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblMenuSet;
    private javax.swing.JTable tblMenuSummary;
    private javax.swing.JTextField tfMemberEdit;
    private javax.swing.JTextField tfMenuEdit;
    private javax.swing.JTextField tfPlaceEdit;
    private javax.swing.JTextField tfPriceMenuEdit;
    private javax.swing.JTextField tfTaxPlaceEdit;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        Home h = new Home();
        Patungan p = new Patungan();
        h.addModel(p);
        h.setVisible(true);
    }

    private Patungan p;
    private Controller c;

    public Home() {
        initComponents();
        c = new Controller();
    }

    public void addModel(Patungan p) {
        this.p = p;
    }

    public void setListener(EventListener event) {
        btnAddMember.addActionListener((ActionListener) event);
        btnAddMemberEdit.addActionListener((ActionListener) event);
        btnAddMemberToPay.addActionListener((ActionListener) event);
        btnAddMenu.addActionListener((ActionListener) event);
        btnAddMenuEdit.addActionListener((ActionListener) event);
        btnAddPlace.addActionListener((ActionListener) event);
        btnAddPlaceEdit.addActionListener((ActionListener) event);
        btnBackMenuSet.addActionListener((ActionListener) event);
        btnCancelMemberEdit.addActionListener((ActionListener) event);
        btnCancelMenuEdit.addActionListener((ActionListener) event);
        btnCancelPlaceEdit.addActionListener((ActionListener) event);
        btnDelMemberToPay.addActionListener((ActionListener) event);
        btnDeleteMember.addActionListener((ActionListener) event);
        btnDeleteMenu.addActionListener((ActionListener) event);
        btnDeletePlace.addActionListener((ActionListener) event);
        btnEditMember.addActionListener((ActionListener) event);
        btnEditMenu.addActionListener((ActionListener) event);
        btnEditPlace.addActionListener((ActionListener) event);
        btnOkPayMember.addActionListener((ActionListener) event);
        btnPay.addActionListener((ActionListener) event);
        btnPayMember.addActionListener((ActionListener) event);
        btnSaveMemberEdit.addActionListener((ActionListener) event);
        btnSaveMenuEdit.addActionListener((ActionListener) event);
        btnSaveMenuSet.addActionListener((ActionListener) event);
        btnSavePlaceEdit.addActionListener((ActionListener) event);
        btnSetBuyer.addActionListener((ActionListener) event);
        btnSetMenu.addActionListener((ActionListener) event);
        listMember.addMouseListener((MouseAdapter) event);

    }

    private class Controller extends MouseAdapter implements ActionListener {

        CardLayout c = (CardLayout) mainPanel.getLayout();

        public Controller() {
            setListener(this);
            c.show(mainPanel, "memberView");
            btnEditMember.setVisible(false);
            btnDeleteMember.setVisible(false);
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            Object e = ae.getSource();
            //Action Handler for Panel Member View
            if (e.equals(btnAddMember)) {
                c.show(mainPanel, "memberEdit");
                btnAddMemberEdit.setVisible(true);
                btnCancelMemberEdit.setVisible(false);
                btnSaveMemberEdit.setVisible(false);
            } else if (e.equals(btnEditMember)) {
                c.show(mainPanel, "memberEdit");
                btnAddMemberEdit.setVisible(false);
                btnCancelMemberEdit.setVisible(true);
                btnSaveMemberEdit.setVisible(true);
            }
//        c.show(mainPanel, "memberEdit");
        }

        public void mousePressed(MouseEvent me) {
            Object e = me.getSource();
            if (e.equals(listMember)) {
                if (listMember.isSelectionEmpty()) {
                    listMember.clearSelection();
                    btnAddMemberEdit.setVisible(true);
                    btnEditMember.setVisible(false);
                    btnDeleteMember.setVisible(false);
                } else {
                    btnAddMemberEdit.setVisible(true);
                    btnEditMember.setVisible(true);
                    btnDeleteMember.setVisible(true);
                }
            }
        }

    }
}
